In [1]:
%run library.ipynb

In [3]:
?banded_matrix

In [5]:
Sigma = banded_matrix(0.4, 10, 2)
Sigma

array([[ 1.  ,  0.4 ,  0.16,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.4 ,  1.  ,  0.4 ,  0.16,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.16,  0.4 ,  1.  ,  0.4 ,  0.16,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.16,  0.4 ,  1.  ,  0.4 ,  0.16,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.16,  0.4 ,  1.  ,  0.4 ,  0.16,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.16,  0.4 ,  1.  ,  0.4 ,  0.16,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.16,  0.4 ,  1.  ,  0.4 ,  0.16,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.16,  0.4 ,  1.  ,  0.4 ,
         0.16],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.16,  0.4 ,  1.  ,  0.4 ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.16,  0.4 ,  1.  ]])

In [16]:
A = banded_matrix(0.2, 5, 1)
A

array([[ 1. ,  0.2,  0. ,  0. ,  0. ],
       [ 0.2,  1. ,  0.2,  0. ,  0. ],
       [ 0. ,  0.2,  1. ,  0.2,  0. ],
       [ 0. ,  0. ,  0.2,  1. ,  0.2],
       [ 0. ,  0. ,  0. ,  0.2,  1. ]])

In [17]:
Q = np.kron(Sigma, A)

In [22]:
X = nr.multivariate_normal(np.zeros(Q.shape[0]), Q).reshape((Sigma.shape[0],-1))

In [24]:
np.corrcoef(X.T)

array([[ 1.        ,  0.22318511,  0.1294484 , -0.43036141,  0.08506907],
       [ 0.22318511,  1.        ,  0.2142602 ,  0.02354603, -0.34149675],
       [ 0.1294484 ,  0.2142602 ,  1.        ,  0.57082351,  0.22350478],
       [-0.43036141,  0.02354603,  0.57082351,  1.        , -0.06463758],
       [ 0.08506907, -0.34149675,  0.22350478, -0.06463758,  1.        ]])

In [ ]:
def compute_S(p, Sigma):
    sd = np.sqrt(2*p*(1-p))
    return(Sigma * sd[:, None] * sd[None, :])

In [ ]:
def simulate_genotypes(Sigma=None, p=None, N=None, binomial=False):
    if Si
    if p is None:
        p = nr.uniform(0.05,0.95)