In [1]:
%run 'library.ipynb'

In [9]:
mean = np.zeros(5)
cov  = banded_matrix(0.4, 5, 2).toarray()
size = 10

In [8]:
N = len(mean)

In [10]:
Zstar = nr.normal(size=(N, size))

Zstar -= Zstar.mean(axis=1)[:,None]

Z = np.linalg.qr(Zstar.T)[0].T * np.sqrt(size)

Sigma12 = np.linalg.cholesky(cov)

X = Sigma12.dot(Z)

np.set_printoptions(precision=3, suppress=True)

X.dot(X.T) / size

X += mean[:,None]

In [47]:
nr.multivariate_normal(mean[:2], cov)

ValueError: mean and cov must have same length

In [46]:
len(cov.shape)

2

In [105]:
def multivariate_normal_sample(mean, cov, bias=True, ddof=None, size=None):
    N = len(mean)

    if len(cov.shape) != 2:
        raise ValueError('cov must be 2 dimensional')

    if cov.shape[0] != cov.shape[1]:
        raise ValueError('cov must be square')
    
    if N != cov.shape[0]:
        raise ValueError('mean and cov must have same length')

    if ddof is None:
        if bias:
            ddof = 0
        else:
            ddof = 1

    if size is None:
        size = N+1
    
    if ddof >= size:
        raise ValueError('ddof must be less than size')

    Z  = nr.normal(size=(N, size))
    Z -= Z.mean(axis=1)[:,None]
    Z  = np.linalg.qr(Z.T)[0].T * np.sqrt(size - ddof)

    Sigma12 = np.linalg.cholesky(cov)

    return(Sigma12.dot(Z) + mean[:,None])

In [103]:
X = multivariate_normal_sample(np.zeros(2), equicorrelation_matrix(0.4, 2), bias=False)

[[ 0.132 -0.642  0.51 ]
 [ 0.957 -0.327 -0.63 ]]
[[-0.225  1.093 -0.868]
 [-1.133  0.372  0.761]]


In [97]:
X.dot(X.T)

array([[ 3. ,  1.2],
       [ 1.2,  3. ]])

In [100]:
X.mean(axis=1)

array([-0., -0.])

In [62]:
X.dot(X.T) / 2

array([[ 1. ,  0.4],
       [ 0.4,  1. ]])

In [101]:
equicorrelation_matrix(0.4, 2)

array([[ 1. ,  0.4],
       [ 0.4,  1. ]])

In [104]:
np.cov(X)

array([[ 1. ,  0.4],
       [ 0.4,  1. ]])

In [75]:
if 4:
    print(True)

True
