In [1]:
import numpy as np
import numpy.random as nr

# Test with normal

In [4]:
X = nr.normal(0, 1, (600,3000))

In [3]:
B = nr.normal(0, 1, 300)

In [5]:
Y = X[:300].T.dot(B)

In [6]:
Bhat1 = np.linalg.inv(X[:300].dot(X[:300].T)).dot(X[:300]).dot(Y)

In [7]:
np.corrcoef(B, Bhat1)

array([[ 1.,  1.],
       [ 1.,  1.]])

In [8]:
Bhat2 = np.linalg.inv(X.dot(X.T)).dot(X).dot(Y)

In [11]:
np.corrcoef(np.hstack([B, np.zeros(300)]), Bhat2)

array([[ 1.,  1.],
       [ 1.,  1.]])

# Test with binomial

In [12]:
X = nr.binomial(2, 0.5, (600,3000))

In [13]:
Y = X[:300].T.dot(B)

In [14]:
Bhat1 = np.linalg.inv(X[:300].dot(X[:300].T)).dot(X[:300]).dot(Y)

In [15]:
np.corrcoef(B, Bhat1)

array([[ 1.,  1.],
       [ 1.,  1.]])

In [16]:
Bhat2 = np.linalg.inv(X.dot(X.T)).dot(X).dot(Y)

In [17]:
np.corrcoef(np.hstack([B, np.zeros(300)]), Bhat2)

array([[ 1.,  1.],
       [ 1.,  1.]])

Double beta distribution

In [2]:
b = ss.beta(1, 2)

In [3]:
b.rvs(100)

array([ 0.04862095,  0.11644809,  0.41385975,  0.08446904,  0.46834205,
        0.17601198,  0.38926977,  0.21150802,  0.65850442,  0.21951928,
        0.69671529,  0.79941834,  0.46063256,  0.2139358 ,  0.35306858,
        0.11364102,  0.01551896,  0.11129527,  0.56743438,  0.36668689,
        0.16933243,  0.0481    ,  0.93498423,  0.4097074 ,  0.51160954,
        0.65662567,  0.3790256 ,  0.50376089,  0.80282885,  0.17460166,
        0.13909594,  0.26622168,  0.17978008,  0.02407864,  0.28712374,
        0.46278362,  0.36056942,  0.39707172,  0.13465761,  0.02951555,
        0.33453228,  0.89880719,  0.30621946,  0.18126133,  0.18287844,
        0.31299245,  0.44463981,  0.23069329,  0.4570391 ,  0.23921839,
        0.04299924,  0.35857749,  0.2226816 ,  0.00976172,  0.19475744,
        0.06550596,  0.10025298,  0.16156202,  0.01109878,  0.70069191,
        0.0189522 ,  0.29476736,  0.78373047,  0.70973265,  0.52175445,
        0.67616191,  0.7229087 ,  0.24545069,  0.17048219,  0.08

In [17]:
ss.bernoulli.rvs(0.5, size=100)*2 - 1

array([-1,  1, -1,  1,  1, -1, -1, -1,  1, -1,  1,  1, -1,  1,  1,  1,  1,
       -1, -1, -1, -1,  1, -1,  1, -1,  1,  1, -1, -1,  1,  1,  1,  1, -1,
        1, -1,  1,  1,  1,  1, -1, -1, -1,  1, -1,  1,  1,  1,  1,  1, -1,
        1,  1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1,  1, -1,  1, -1, -1,
        1, -1,  1,  1,  1,  1,  1,  1, -1, -1,  1, -1, -1, -1,  1,  1,  1,
        1, -1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1])

In [38]:
class dbeta:
    def __init__(self, *args, **kwargs):
        self.beta = ss.beta(*args, **kwargs)

    def rvs(self, *args, **kwargs):
        rvs = self.beta.rvs(*args, **kwargs)
        if type(rvs) is float:
            scale = ss.bernoulli.rvs(0.5)*2 - 1
        else:
            scale = ss.bernoulli.rvs(0.5, size=rvs.shape)*2 - 1
        return rvs*scale
    
    def cdf()

In [39]:
d = dbeta(1,2)

In [43]:
d.rvs((10,2))

array([[-0.24035856, -0.10971691],
       [ 0.89497979,  0.15781412],
       [ 0.48657566, -0.00671175],
       [ 0.38191796, -0.2581871 ],
       [ 0.51511362,  0.54795441],
       [-0.01967323, -0.68327563],
       [-0.28496144,  0.57757288],
       [ 0.13952198,  0.72816153],
       [ 0.50954176, -0.49223973],
       [-0.18198242,  0.15635716]])